### ISSUE TITLE
Provide simple property to opt out of static proxies

### ISSUE THREAD

**Issue by kzu** [kzu/avatar#48]
Dynamic proxies based on Castle.Core are super stable, well supported and have stood the test of time.

Static proxies based on source generators are brand-new and therefore lack the broad testing in the wild, so it should be very easy (and with a documented property) to turn them off if things don't quite work for particular scenarios.

Proposed property: `EnableCompiledAvatars`. Not mentioning "source generator" in the property since that's an implementation detail people may not easily recognize, and "compiled" conveys that these are things that happen at compile-time, rather than run-time like the dynamic proxies (which are better known).

The property should be `true` by default whenever the project supports source generators (C#9+).

**Comment by stakx** [comment]
> Proposed property: `EnableCompiledAvatars`. Not mentioning "source generator" in the property since that's an implementation detail people may not easily recognize, and "compiled" conveys that these are things that happen at compile-time, rather than run-time

I generally agree, esp. with the first part; however, `Compiled` by itself may not necessarily equate "compile-time". For example, `Regex`es can be "compiled", but that's a process that (AFAIK) happens at run-time. 

If you don't mind long names, you might want to consider being safer by a more specific name like `EnableCompileTime[Generated]Avatars`.

**Comment by kzu** [comment]
Well, AFAIK, that regex situation is very likely to change too to use source generators to speed up run-time, yet the option in the API will still be called RegexOptions.Compiled 🤔. I wanted to keep the property short-ish, but `EnableCompileTimeAvatars` isn't too bad. Then the Castle.Core-based ones would be `EnableRunTimeAvatars`?

**Comment by stakx** [comment]
> yet the option in the API will still be called RegexOptions.Compiled

Good point.

If you prefer short names, the ones you've already got now seem fine, as do the ones you suggested above.
