### ISSUE TITLE
Allow invoking base (virtual) method directly from IMethodInvocation

### ISSUE THREAD

**Issue by kzu** [kzu/avatar#56]
Based on feedback from @stakx, it looks like the way we currently implement CallBase in Moq is quite convoluted (it involves skipping other behaviors dynamically, tightly coupling the call base behavior to the other configured behaviors).

Instead of that, just add a new API to the `IMethodInvocation` to directly create a return by calling the base method. Proposal:

```csharp
IMethodReturn CreateCallBaseReturn(IArgumentCollection? arguments = null);
```

The optional `arguments` would allow the caller/behavior to perform any last-minute tweaks to the arguments ultimately used in the base call prior to returning a value (and optional ref/out args).

This also means we can simplify the behavior pipeline API itself, since there would be no concept of a *target* to invoke, just the pipeline itself. The pipeline would need to be modified so that invoking it for a method with no implementation (abstract or interface) and with no configured behaviors, throws `NotImplementedException` now automatically.

**Comment by stakx** [comment]
Good to hear that this would indeed make it possible to simplify the pipeline architecture.

> The pipeline would need to be modified so that invoking it for a method with no implementation (abstract or interface) and with no configured behaviors, throws NotImplementedException now automatically.

That appears to match Castle DynamicProxy's behavior, :+1: as it facilitates swapping between the two technologies upstream.

> ```csharp
> IMethodReturn CreateCallBaseReturn(IArgumentCollection? arguments = null);
> ```
>
> The optional `arguments` would allow the caller/behavior to perform any last-minute tweaks to the arguments ultimately used in the base call prior to returning a value (and optional ref/out args).

Does the returned `IMethodReturn` represent the result of calling the base method implementation? That is, will the base method be called right away? If so :+1: as that would allow you to not just tweak the base method's inputs, but also its outputs.

**Comment by kzu** [comment]
Great questions 💯 

> Does the returned IMethodReturn represent the result of calling the base method implementation?

Yes, indeed. But modifying the return isn't currently as straightforward since the implementation of `IMethodReturn` is not public. Maybe it should be public so you can modify it? Alternatively, perhaps we could have mutating methods in the `IMethodReturn` like `WithArguments`, `WithReturnValue` and `WithException`, say?

> Is it permissible to call this method more than once?

I'm not limiting that in the pipeline at all, so technically yes. It wouldn't be a recorded invocation through the pipeline though (no further behaviors applied either, it's a straight delegate to the implementation inside the generated proxy).

**Comment by stakx** [comment]
Great to hear that the base method call's output(s) _can_ in principle be modified; that was really my main concern here.

> Maybe it should be public so you can modify it? Alternatively, perhaps we could have mutating methods in the `IMethodReturn` like `WithArguments`, `WithReturnValue` and `WithException`, say?

I would keep the `IMethodReturn` implementation private, in order to keep the public API surface as minimal as possible &ndash; less maintenance, plus more freedom to refactor internals, if needed.

A bunch of `With...` method sounds useful. They would be a nice fit for the current "immutable type" design and C# 9's new `with` expressions for record types.

Even if you don't add those methods, one could still reimplement `IMethodReturn` and copy over properties from the original instance to a custom instance, right? That would be some work, but it would be possible; that's the main thing IMHO.

**Comment by kzu** [comment]
Yeah, maybe. The thing is that the `MethodReturn` implementation is really trivial. Moreover, someone inspecting the API might wonder why did I make `MethodInvocation` and `ArgumentCollection` public and not the `MethodReturn`? The answer is not trivial, of course: the first two are used in generated proxy/avatar code and therefore *have* to be public, but at face value, it seems like a weird design choice and a (however minor) friction point for extensibility in the pipeline... dunno...
